server:
  port: 53010

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:53020/uaa/oauth2/jwks
  cloud:
    nacos:
      discovery:
        server-addr: localhost
    sentinel:
      transport:
        dashboard: localhost:8080
    gateway:
      globalcors:
        '[/**]': #匹配所有请求
          allowedOrigins: "*" #跨域处理
          allowedMethods:  #支持的方法
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
      routes:
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: uaa
          uri: lb://uaa-service
          predicates:
            - Path=/uaa/**

logging:
  level:
    root: info

