server:
  port: 53021
  servlet:
    context-path: /order

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://loaclhost:3306/user_db?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:53020/uaa/oauth2/jwks
#          issuer-uri: http://localhost:53020/uaa
  cloud:
    nacos:
      discovery:
        server-addr: localhost
    sentinel:
      transport:
        dashboard: localhost:8080

logging:
  level:
    root: info
    org.springframework.security: debug